# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: "Quire & You"
title: "Quire & You"
email: feedback@quire.io
description: "A collaborative task management tool for breaking down goals in hierarchical lists."
baseurl: "/guide" # the subpath of your site, e.g. /blog
url: "https://quire.io" # the base hostname & protocol for your site, e.g. http://example.com
# dev_url: "http://127.0.0.1:4000"
twitter_username: jekyllrb
github_username:  jekyll
search: true
search_provider: google
google:
  search_engine_id: 005233953568477628153:b1ykntxgopi
  instant_search: true
collections:
  docs:
    output: true
    permalink: /:path/

comments:
    provider: "disqus"
    disqus:
      shortname: "guide-1"

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      classes: wide
      read_time: false
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "docs"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  # - jekyll-feed

after_footer_scripts:
  /assets/js/custom-footer.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
